// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio_ZoranSimeunovic.Data;

#nullable disable

namespace Portfolio_ZoranSimeunovic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622201725_AddDocuments")]
    partial class AddDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ChecklistAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactLeadId")
                        .HasColumnType("int")
                        .HasColumnName("contact_lead_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("item_text");

                    b.Property<string>("ListKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("list_key");

                    b.HasKey("Id");

                    b.HasIndex("ContactLeadId");

                    b.ToTable("checklist_answers", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ClientAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action_type");

                    b.Property<int>("ContactLeadId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("executed_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactLeadId");

                    b.ToTable("client_actions", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ContactLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("OfferSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OptedOut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("contact_leads", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<int>("ContactLeadId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("stage");

                    b.Property<string>("Step1Answers")
                        .HasColumnType("longtext")
                        .HasColumnName("step1_answers");

                    b.Property<string>("Step2Answers")
                        .HasColumnType("longtext")
                        .HasColumnName("step2_answers");

                    b.Property<string>("Step3Answers")
                        .HasColumnType("longtext")
                        .HasColumnName("step3_answers");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactLeadId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("questionnaire", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ChecklistAnswer", b =>
                {
                    b.HasOne("Portfolio_ZoranSimeunovic.Models.ContactLead", "ContactLead")
                        .WithMany()
                        .HasForeignKey("ContactLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLead");
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ClientAction", b =>
                {
                    b.HasOne("Portfolio_ZoranSimeunovic.Models.ContactLead", "ContactLead")
                        .WithMany()
                        .HasForeignKey("ContactLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLead");
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.Questionnaire", b =>
                {
                    b.HasOne("Portfolio_ZoranSimeunovic.Models.ContactLead", "ContactLead")
                        .WithMany()
                        .HasForeignKey("ContactLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLead");
                });
#pragma warning restore 612, 618
        }
    }
}
