// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio_ZoranSimeunovic.Data;

#nullable disable

namespace Portfolio_ZoranSimeunovic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622124601_AddQuestionnaireAndClientActions")]
    partial class AddQuestionnaireAndClientActions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ChecklistAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ContactLeadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_lead_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_text");

                    b.Property<string>("ListKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("list_key");

                    b.HasKey("Id");

                    b.HasIndex("ContactLeadId");

                    b.ToTable("checklist_answers", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ClientAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<int>("ContactLeadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("executed_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactLeadId");

                    b.ToTable("client_actions", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ContactLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contact_leads", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("ContactLeadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<byte>("Stage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stage");

                    b.Property<string>("Step1Answers")
                        .HasColumnType("TEXT")
                        .HasColumnName("step1_answers");

                    b.Property<string>("Step2Answers")
                        .HasColumnType("TEXT")
                        .HasColumnName("step2_answers");

                    b.Property<string>("Step3Answers")
                        .HasColumnType("TEXT")
                        .HasColumnName("step3_answers");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactLeadId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("questionnaire", (string)null);
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ChecklistAnswer", b =>
                {
                    b.HasOne("Portfolio_ZoranSimeunovic.Models.ContactLead", "ContactLead")
                        .WithMany()
                        .HasForeignKey("ContactLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLead");
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.ClientAction", b =>
                {
                    b.HasOne("Portfolio_ZoranSimeunovic.Models.ContactLead", "ContactLead")
                        .WithMany()
                        .HasForeignKey("ContactLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLead");
                });

            modelBuilder.Entity("Portfolio_ZoranSimeunovic.Models.Questionnaire", b =>
                {
                    b.HasOne("Portfolio_ZoranSimeunovic.Models.ContactLead", "ContactLead")
                        .WithMany()
                        .HasForeignKey("ContactLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLead");
                });
#pragma warning restore 612, 618
        }
    }
}
